version: '3'

services:
  app:
    image: ruby:2.7
    build: ./docker/app
    volumes:
      - ".:/app"
      - "vendor-bundle:/usr/local/bundle"
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      RAILS_ENV: development
      BINDING: 0.0.0.0
      BUNDLE_JOBS: 2
    command:
      - 'tail'
      - '-f'
      - '/dev/null'
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  vendor-bundle:
    driver: local
